import React, { useState } from "react";
import mobileImage from "../assets/cat.gif"; // Adjust the path accordingly

const Features = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleAccordion = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const userFeatures = [
    { title: "QR Based Check-in & Check-out's", content: "Visitors can check-in & create their digital passes by scanning the QR codes pasted at the entrance of your premises. Entire process will be done over their own phones without downloading any application. They can check-out on their way out, just by scanning a QR code." },
    { title: "No Dependency on hardware or App downloads", content: "This mobile first platform is designed to function with any hardware or application downloads, to reduce carbon footprints & minimize physical touch points. This in return results in no long queues at the reception." },
    { title: "WhatsApp based Visitor approvals", content: "Receive details of your visitors on WhatsApp & Approve, Reject or Reschedule them based on your availability. Pass will only be issued post your confirmation." },
    { title: "Digital Visitor Passes", content: "Visitors get their digital passes on WhatsApp, which can be displayed to the verification Team at the time of entry. Each pass has a unique QR code, which can be scanned by the verification Team members to verify its validity." },
    { title: "Digital Employee Passes", content: "Remove physical ID cards and start issuing Digital employee passes. Two types of employee passes are available, a company pass which is issued once and is valid for a longer duration and i work here pass which is created on a daily basis." },
    { title: "Pre-invite Guests", content: "Pre-Invite visitors for a faster and smoother check-in experience. These invites are sent over WhatsApp." },
    { title: "Pass Verification by verification team members", content: "Verification team members can scan the unique QR code present on each pass to verify its validity." }
  ];

  const adminFeatures = [
    { title: "Account Analytics", content: "Full analytics & usage of your account represented graphically. One single screen to monitor the entire usage." },
    { title: "Downloadable QR Codes", content: "Download Check-in, check-out & pre-invite QR codes of all offices from here in PDF & PNG files. The same should be printed and pasted at respective locations. You can even copy the URL & share when required." },
    { title: "Visitor Logs", content: "This screen has complete details of all unique visitors along with all the passes generated by them. Find all unique visitors for your workspace here." },
    { title: "Visitor List", content: "Send invites one by one or in bulk from here. You can also issue company passes to your contractual or full time workforce and set validity periods for the same. VIP passes are also available which are sent directly over whatsApp and do not require any check-in by the visitor." },
    { title: "Blacklist Users", content: "Blacklist visitors or staff from here. Once blacklisted, a user will never be able to create a pass at your premises." },
    { title: "Employee List", content: "Add employees one by one or in bulk from this screen along with their departments. The same details will be used for visitor approval. This is an optional feature." },
    { title: "Office wise Admin Access", content: "Assign Office & product wise access to admins. They will only have access to details of offices and products which are assigned to them." },
    { title: "Verification Team members", content: "Add verification team members to each office along with their name & number. These users can login to their account to verify validity of visitor passes by scanning the QR available on each digital pass." }
  ];

  return (
    <>
      {/* User Features Section */}
      <div className="flex flex-col lg:flex-row items-center gap-8 p-6 lg:p-12">
        <div className="relative w-full lg:w-1/2 flex justify-center">
          <img src={mobileImage} alt="Mobile UI" className="w-80 md:w-96 lg:w-[400px]" />
        </div>
        <div className="w-full lg:w-1/2">
          <h2 className="text-4xl text-center text-pink-800 mb-4 font-semibold">User Side Features</h2>
          <div className="space-y-3 text-black text-lg">
            {userFeatures.map((item, index) => (
              <div key={index} className="collapse collapse-arrow rounded-lg ">
                <input type="checkbox" id={`accordion-${index}`} checked={openIndex === index} onChange={() => toggleAccordion(index)} />
                <label htmlFor={`accordion-${index}`} className="collapse-title text-sm cursor-pointer block ">
                  {item.title}
                </label>
                {openIndex === index && (
                  <div className="collapse-content text-sm text-pink-800">{item.content}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      <hr className="w-full border-pink-800 mb-8" />

      {/* Admin Features Section */}
      <div className="flex flex-col lg:flex-row items-center gap-8 p-6 lg:p-12">
        <div className="w-full lg:w-1/2">
          <h2 className="text-4xl text-center text-pink-800 font-semibold mb-4">Admin Side Features</h2>
          <div className="space-y-3 text-black">
            {adminFeatures.map((item, index) => (
              <div key={index} className="collapse collapse-arrow rounded-lg">
                <input type="checkbox" id={`admin-accordion-${index}`} checked={openIndex === `admin-${index}`} onChange={() => toggleAccordion(`admin-${index}`)} />
                <label htmlFor={`admin-accordion-${index}`} className="collapse-title text-sm cursor-pointer block">
                  {item.title}
                </label>
                {openIndex === `admin-${index}` && (
                  <div className="collapse-content text-sm text-pink-800">{item.content}</div>
                )}
              </div>
            ))}
          </div>
        </div>
        <div className="relative w-full lg:w-1/2 flex justify-center">
          <img src={mobileImage} alt="Mobile UI" className="w-80 md:w-96 lg:w-[400px]" />
        </div>
      </div>

      <hr className="w-full border-pink-800 mb-8" />
    </>
  );
};

export default Features;
